'use strict';

const { MA_THIET_LAP } = require('../cau-hinh.constants');

const THIET_LAP_KHONG_CHO_CHON_CO_SO = new Set([
    MA_THIET_LAP.TEN_HE_THONG,
    MA_THIET_LAP.LOGO_CO_SO_MAC_DINH,
    MA_THIET_LAP.SO_LAN_DANG_NHAP_SAI_TOI_DA,
    MA_THIET_LAP.THOI_GIAN_KHOA_TAI_KHOAN,
    MA_THIET_LAP.THOI_GIAN_ACCESS_TOKEN,
    MA_THIET_LAP.THOI_GIAN_REFRESH_TOKEN,
    MA_THIET_LAP.THOI_GIAN_TIMEOUT,
    MA_THIET_LAP.SIDEBAR_MAC_DINH_DONG
]);

const THIET_LAP_BAT_BUOC_CO_SO = new Set([

]);

module.exports = {
    THIET_LAP_KHONG_CHO_CHON_CO_SO,
    THIET_LAP_BAT_BUOC_CO_SO
};